#pragma once

/* Primitive types: directly map to types used in Nintendo's blobs */
#include <cstdint>
using u8 = std::uint8_t;
using u16 = std::uint16_t;
using u32 = std::uint32_t;
using u64 = std::uint64_t;

using s8 = std::int8_t;
using s16 = std::int16_t;
using s32 = std::int32_t;
using s64 = std::int64_t;

struct vec2f { float x, y; };
struct vec3f { float x, y, z; };

#include "External/String.hpp"
using string16 = string<16>;
using string32 = string<32>;
using string64 = string<64>;

using wchar = char16_t;
template <size_t N> using wstring = u16string<N>;
using wstring16 = wstring<16>;
using wstring32 = wstring<32>;
using wstring64 = wstring<64>;

using byte = unsigned char;

/* MurmurHash3: Nintendo uses the 32 bit version in it's blobs */
#include "External/MurmurHash3.hpp"
using hash_t = mmh32;

/* STL types
 * Sage automatically upgrades
 * C style arrays into array-view (std::span)
 * while C strings can be implicitly upgraded in user code */
#include <span>
template<typename T>
using array = std::span<T>;

/* GameData Tags
 * These types are used in Sage's GameData model,
 * for constraining template substitution
 * in Sage's Sav::get<[S|M]> API */
namespace Tag
{
    struct Type {};
    struct Structure : Type {};
    struct Member : Type {};
    struct Enum : Member {};
}

namespace Data
{
    /* This template will be specialised with
     * auto generated constructible copies of structure types
     * keyed using corresponding tag (subclass of Tag::Structure) */
    template <typename S>
    requires std::derived_from<S, Tag::Structure>
    struct Structure;

    /* This template will be specialised
     * to store autogenerated hashes for member types
     * keyed using corresponding tag (subclass of Tag::Member) */
    template <typename M>
    requires std::derived_from<M, Tag::Member>
    inline constexpr hash_t Hashtable = [] {
        /* This static assert ensures that no other type
         * can fall back to this non-specialised template (because this is not an impl)
         * -- we throw a hard error for undefined specializations. */
        static_assert(false, "no hashtable entry found");
    };
}