#pragma once

#include "Core/Types.hpp"
#include "Core/Layout.hpp"
#include "Core/Model/Tag.hpp"

namespace Data
{
    /* This template will be specialised with
     * auto generated constructible copies of structure types
     * keyed using corresponding tag (subclass of Tag::Structure) */
    template <typename S>
    requires std::derived_from<S, Tag::Structure>
    struct Structure;

    /* This template will be specialised
     * to store autogenerated hashes for member types
     * keyed using corresponding tag (subclass of Tag::Member) */
    template <typename M>
    requires std::derived_from<M, Tag::Member>
    inline constexpr hash_t Hashtable = [] {
        /* This static assert ensures that no other type
         * can fall back to this non-specialised template (because this is not an impl)
         * -- we throw a hard error for undefined specializations. */
        static_assert(false, "no hashtable entry found");
        return 0;
    }();

    template <typename M, typename P = M::type, typename I = std::remove_pointer_t<P>, typename L = Layout<I>, typename O = L::to_type>
    using Member = O;

    template <typename E, typename O = Member<E>>
    using Enum = O;
}
