#pragma once
#include "Core/Types.hpp"
#include "Core/Enum.hpp"
#include "Core/Sav.hpp"

struct GameData::SortPattern : Tag::Structure {
	struct Pouch_Armor : Tag::Enum { using type = ::Enum::Scalar<Pouch_Armor>; using adapter = ::Enum::Scalar<Pouch_Armor>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
	struct Pouch_Bow : Tag::Enum { using type = ::Enum::Scalar<Pouch_Bow>; using adapter = ::Enum::Scalar<Pouch_Bow>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
	struct Pouch_Food : Tag::Enum { using type = ::Enum::Scalar<Pouch_Food>; using adapter = ::Enum::Scalar<Pouch_Food>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
	struct Pouch_KeyItem : Tag::Enum { using type = ::Enum::Scalar<Pouch_KeyItem>; using adapter = ::Enum::Scalar<Pouch_KeyItem>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
	struct Pouch_Material : Tag::Enum { using type = ::Enum::Scalar<Pouch_Material>; using adapter = ::Enum::Scalar<Pouch_Material>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
	struct Pouch_Shield : Tag::Enum { using type = ::Enum::Scalar<Pouch_Shield>; using adapter = ::Enum::Scalar<Pouch_Shield>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
	struct Pouch_SpecialParts : Tag::Enum { using type = ::Enum::Scalar<Pouch_SpecialParts>; using adapter = ::Enum::Scalar<Pouch_SpecialParts>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
	struct Pouch_Weapon : Tag::Enum { using type = ::Enum::Scalar<Pouch_Weapon>; using adapter = ::Enum::Scalar<Pouch_Weapon>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
	struct ShortCut_Bow : Tag::Enum { using type = ::Enum::Scalar<ShortCut_Bow>; using adapter = ::Enum::Scalar<ShortCut_Bow>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
	struct ShortCut_Material : Tag::Enum { using type = ::Enum::Scalar<ShortCut_Material>; using adapter = ::Enum::Scalar<ShortCut_Material>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
	struct ShortCut_Shield : Tag::Enum { using type = ::Enum::Scalar<ShortCut_Shield>; using adapter = ::Enum::Scalar<ShortCut_Shield>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
	struct ShortCut_Weapon : Tag::Enum { using type = ::Enum::Scalar<ShortCut_Weapon>; using adapter = ::Enum::Scalar<ShortCut_Weapon>; enum enum_type : hash_t { None = murmurhash3::hash("None"), Weapon_Category = murmurhash3::hash("Weapon_Category"), Shield_Strength = murmurhash3::hash("Shield_Strength"), Bow_Strength = murmurhash3::hash("Bow_Strength"), Armor_Cateogry = murmurhash3::hash("Armor_Cateogry"), Armor_Series = murmurhash3::hash("Armor_Series"), Material_Category = murmurhash3::hash("Material_Category"), Material_ScraBuild = murmurhash3::hash("Material_ScraBuild"), Material_UseCounter = murmurhash3::hash("Material_UseCounter"), Material_SpecialParts = murmurhash3::hash("Material_SpecialParts"), Food_Effect = murmurhash3::hash("Food_Effect"), SpecialParts_Sortkey = murmurhash3::hash("SpecialParts_Sortkey"), KeyItem_SortKey = murmurhash3::hash("KeyItem_SortKey"), }; };
};/* Tag::Structure GameData::SortPattern close */

template <> struct Data::Structure<GameData::SortPattern> : GameData::SortPattern {
	Pouch_Armor::type Pouch_Armor;
	Pouch_Bow::type Pouch_Bow;
	Pouch_Food::type Pouch_Food;
	Pouch_KeyItem::type Pouch_KeyItem;
	Pouch_Material::type Pouch_Material;
	Pouch_Shield::type Pouch_Shield;
	Pouch_SpecialParts::type Pouch_SpecialParts;
	Pouch_Weapon::type Pouch_Weapon;
	ShortCut_Bow::type ShortCut_Bow;
	ShortCut_Material::type ShortCut_Material;
	ShortCut_Shield::type ShortCut_Shield;
	ShortCut_Weapon::type ShortCut_Weapon;
	
	explicit Structure(Sav& s) : 
		Pouch_Armor { s.get<struct Pouch_Armor>() },
		Pouch_Bow { s.get<struct Pouch_Bow>() },
		Pouch_Food { s.get<struct Pouch_Food>() },
		Pouch_KeyItem { s.get<struct Pouch_KeyItem>() },
		Pouch_Material { s.get<struct Pouch_Material>() },
		Pouch_Shield { s.get<struct Pouch_Shield>() },
		Pouch_SpecialParts { s.get<struct Pouch_SpecialParts>() },
		Pouch_Weapon { s.get<struct Pouch_Weapon>() },
		ShortCut_Bow { s.get<struct ShortCut_Bow>() },
		ShortCut_Material { s.get<struct ShortCut_Material>() },
		ShortCut_Shield { s.get<struct ShortCut_Shield>() },
		ShortCut_Weapon { s.get<struct ShortCut_Weapon>() }
	{ }
};/* Data::Structure GameData::SortPattern close */

template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::Pouch_Armor> = murmurhash3::hash("SortPattern.Pouch_Armor");
template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::Pouch_Bow> = murmurhash3::hash("SortPattern.Pouch_Bow");
template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::Pouch_Food> = murmurhash3::hash("SortPattern.Pouch_Food");
template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::Pouch_KeyItem> = murmurhash3::hash("SortPattern.Pouch_KeyItem");
template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::Pouch_Material> = murmurhash3::hash("SortPattern.Pouch_Material");
template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::Pouch_Shield> = murmurhash3::hash("SortPattern.Pouch_Shield");
template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::Pouch_SpecialParts> = murmurhash3::hash("SortPattern.Pouch_SpecialParts");
template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::Pouch_Weapon> = murmurhash3::hash("SortPattern.Pouch_Weapon");
template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::ShortCut_Bow> = murmurhash3::hash("SortPattern.ShortCut_Bow");
template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::ShortCut_Material> = murmurhash3::hash("SortPattern.ShortCut_Material");
template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::ShortCut_Shield> = murmurhash3::hash("SortPattern.ShortCut_Shield");
template <> hash_t constexpr Data::Hashtable<GameData::SortPattern::ShortCut_Weapon> = murmurhash3::hash("SortPattern.ShortCut_Weapon");