#pragma once

#include "Core/Types.hpp"
#include "Core/Layout.hpp"
#include "Core/Overlay/Tag.hpp"

namespace Data
{
    /* This template will be specialised with
     * auto generated constructible copies of structure types
     * keyed using corresponding tag (subclass of Tag::Structure) */
    template <typename S>
    requires std::derived_from<S, Tag::Structure>
            || std::derived_from<S, Tag::Map>
    struct Structure;

    /* This template will be specialised
     * to store autogenerated hashes for member types
     * keyed using corresponding tag (subclass of Tag::Member) */
    template <typename M>
    requires std::derived_from<M, Tag::Member>
    inline constexpr hash_value_t Hashtable = [] {
        /* This static assert ensures that no other type
         * can fall back to this non-specialised template (because this is not an impl)
         * -- we throw a hard error for undefined specializations. */
        static_assert(false, "no hashtable entry found");
        return 0;
    }();

    template
        <typename M,
        typename Q = M::type,
        typename P = std::remove_reference_t<Q>,
        typename V = std::remove_pointer_t<P>,
        typename I = std::conditional_t<std::is_reference_v<Q>, V&, V>,
        typename L = Layout<I>,
        typename O = L::to_type>
    using Member = O;

    template <typename E, typename O = Member<E>>
    using Enum = O;

    template <typename N, typename I = Structure<N>, typename U = I::type, typename A = map<U, sizeof(I) / sizeof(void*)>, typename L = Layout<A>, typename O = L::to_type>
    using Map = O;
}

/*
 * User-facing instance types, can be used to strongly type
 * values returned by the tag types (like in function parameters)
 * See Examples/Sample.cpp
 */
using Data::Structure, Data::Member, Data::Enum, Data::Map;
